// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPNOJjuz0klMTcyGWRqxZo3FcR76VXwlM',
    appId: '1:996606585770:web:4b980f7fd78250490459d3',
    messagingSenderId: '996606585770',
    projectId: 'todo-list-d0c42',
    authDomain: 'todo-list-d0c42.firebaseapp.com',
    storageBucket: 'todo-list-d0c42.firebasestorage.app',
    measurementId: 'G-57CNTHJEMX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUoj-JgrEPu0YxqJwb5ku8hFpsSJkEqNA',
    appId: '1:996606585770:android:888461d8332f04530459d3',
    messagingSenderId: '996606585770',
    projectId: 'todo-list-d0c42',
    storageBucket: 'todo-list-d0c42.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtPcQyGCv0gKgnhoi9tUcyhbrtOEBPn4g',
    appId: '1:996606585770:ios:91fb4c9450bbab870459d3',
    messagingSenderId: '996606585770',
    projectId: 'todo-list-d0c42',
    storageBucket: 'todo-list-d0c42.firebasestorage.app',
    iosBundleId: 'com.example.todoList',
  );
}
